name: Deploy Courses Website

on:
  push:
    branches:
      - main  # ou 'master', vérifiez le nom de votre branche principale

env:
  PROJECT_ID: geometric-orbit-229721   # À REMPLACER (ex: mon-projet-123)
  REGION: europe-west1               # À REMPLACER (ex: Paris)
  SERVICE_NAME: courses-website      # C'est le nom exact de votre nouveau service

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authentification via la clé JSON (méthode simple)
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Afficher le compte de service utilisé
        run: gcloud config list account --format "value(core.account)"
  
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push Container
        run: |-
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

